# Generated by Django 5.0.4 on 2024-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tag_status_alter_tag_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='tags', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tags', to='webapp.type', verbose_name='Тип'),
        ),
    ]
