# Generated by Django 5.0.4 on 2024-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_tag_status_remove_tag_type_tag_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Время обновления')),
            ],
        ),
    ]
